const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
    variants: {
        extend: {
            transform: ["hover"],
            scale: ["hover"],
            lineClamp: ["responsive", "hover"],
            boxShadow: ["dark"],
        },
    },

    corePlugins: {
        borderOpacity: true,
        scale: true,
        transform: true,
    },
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./vendor/laravel/jetstream/**/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./node_modules/flowbite-vue/**/*.{js,jsx,ts,tsx}",
        "./node_modules/flowbite/**/*.{js,jsx,ts,tsx}",
        "./node_modules/sortablejs/**/*.js",
        "./vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],

    safelist: [
        "w-64",
        "w-72",
        "w-1/2",
        "rounded-l-lg",
        "rounded-r-lg",
        "bg-gray-200",
        "grid-cols-4",
        "grid-cols-7",
        "h-6",
        "leading-6",
        "h-9",
        "leading-9",
        "shadow-lg",
        "bg-opacity-50",
        "rounded-full",
        "dark:bg-opacity-80",
        "bg-gray-900",
        "dark:bg-gray-50",
        "xs:hidden",
        "sm:hidden",
        "md:hidden",
        "lg:hidden",
        "sm:block",
        "md:block",
        "lg:block",
        "sm:flex",
        "md:flex",
        "lg:flex",
        "text-sm",
        "h-44",
        "text-center",
        "text-left",
        "text-right",
        "rounded-lg-t",
        "hover:bg-gray-300",
        "dark:bg-gray-700",
        "hover:dark:bg-gray-800",
        "z-10",
        "hover:dark:bg-gray-700",
        "z-50",
        "pr-3",
        "hover:bg-gray-300",
        "xs:grid-cols-1",
        "sm:grid-cols-1",
        "md:grid-cols-2",
        "lg:grid-cols-3",
        "disabled:opacity-75",
        "-p-6",
        "xs:flex-col",
        "if-xs",
        "if-sm",
        "if-md",
        "if-lg",
        "xs:space-y-3",
        "md:space-y-0",
        "pl-5",
        "pr-1",
        "ml-20",
        "hover:scale-150",
        "text-4xl",
        "text-3xl",
        "font-extrabold",
        "bg-yellow-500",
        "rounded-bl-lg",
        "rounded-br-lg",
        "dark:border-green-600",
        "my-auto",
        "pr-5",
        "py-5",
        "truncate",
        "min-w-max",
        "w-64",
        "w-80",
        "w-3/4",
        "text-md",
        "border-yellow-400",
        "dark:border-yellow-400",
        "xs:gap-0",
        "md:gap-5",
        "shadow-info",
        "shadow-success",
        "shadow-warning",
        "shadow-danger",
        "shadow-dark",
        "shadow-primary",
        "px-4",
        "py-4",
        "lg:ml-[4rem]",
        "lg:ml-[16rem]",
        "pl-14",
        "rounded-tl-lg",
        "rounded-tr-lg",
        "rounded-b-lg",
    ],
    darkMode: "class",
    theme: {
        extend: {
            screens: {
                xs: "0px",
                sm: "600px",
                md: "768px",
                lg: "976px",
                xl: "1440px",
            },
            boxShadow: {
                blue: "0 1px 2px 0 rgba(0, 0, 255, 0.05), 0 1px 3px 1px rgba(0, 0, 255, 0.1)",
            },
            colors: {
                transparent: "transparent",
                current: "currentColor",
                primary: {
                    50: "#f8fafc",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                },
                darkish: {
                    50: "#f8fafc",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#131722",
                    900: "#1e3a8a",
                },
            },

            lineClamp: {
                2: "2",
                3: "3",
                4: "4",
                5: "5",
                6: "6",
                7: "7",
                8: "8",
            },
            fontFamily: {
                sans: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                mono: [
                    "ui-monospace",
                    "SFMono-Regular",
                    "Menlo",
                    "Monaco",
                    "Consolas",
                    "Liberation Mono",
                    "Courier New",
                    "monospace",
                ],
            },
            transitionProperty: {
                width: "width",
            },
            textDecoration: ["active"],
        },
    },

    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/typography"),
        require("flowbite/plugin"),
        require("tailwindcss-dark-mode")(),
    ],
};
